get rid of fuse2fs warnings, update to 4.21

diff --git a/cvmfsexec b/cvmfsexec
--- a/cvmfsexec
+++ b/cvmfsexec
@@ -9,7 +9,7 @@
 #set -x
 #PS4='c$$+ '
 
-VERSION=4.20
+VERSION=4.21
 
 usage()
 {
@@ -275,9 +275,25 @@ unshare -rm $UNSHAREOPTS /bin/bash /dev/stdin "${@:-$SHELL}" <<!EOF-1!
         fi
     done <&$STDINCOPYFD {CMDINFD}<$CMDFIFO2
     # shutting down
-    if $USERFUSE && [ -z "$UNSHAREOPTS" ]; then
-        # automatic cleanup doesn't happen in this case, so unmount all
+    if [ -n "$E2FSIMAGE" ] || ($USERFUSE && [ -z "$UNSHAREOPTS" ]); then
+        # automatic cleanup doesn't happen in these cases, so unmount all
         proccmd -n UMOUNTALL
+        if [ -n "$E2FSIMAGE" ]; then
+            # wait a little for fuse processes to exit
+            umountwait() {
+                N=0
+                while [ "\$N" -lt 20 ]; do
+                    if [ -z "\$(ps -e|grep \$1)" ]; then
+                        break
+                    fi
+                    sleep 0.1
+                    let N+=1
+                done
+            }
+            umountwait cvmfs2
+            umount /e2fs
+            umountwait fuse2fs
+        fi
     fi
     ) &
     
@@ -303,7 +319,7 @@ unshare -rm $UNSHAREOPTS /bin/bash /dev/stdin "${@:-$SHELL}" <<!EOF-1!
         if [ "$E2FSIMAGE" != "" ]; then
             echo "Mounting $E2FSIMAGE at /e2fs"
             mkdir -p /e2fs
-            PATH=$PATH:$HERE/dist/usr/sbin fuse2fs $E2FSIMAGE /e2fs
+            PATH=$PATH:$HERE/dist/usr/sbin LD_LIBRARY_PATH=$HERE/dist/usr/lib64:$HERE/dist/usr/lib fuse2fs $E2FSIMAGE /e2fs
         fi
 
         # mount the initial repos
@@ -332,6 +348,9 @@ unshare -rm $UNSHAREOPTS /bin/bash /dev/stdin "${@:-$SHELL}" <<!EOF-1!
         # running without new process namespace, so more cleanup
         #  needs to be done and our exit needs to wait for the
         #  background process to finish cleaning up
+        EXEC=""
+    elif [ -n "$E2FSIMAGE" ]; then
+        # fuse2fs complains if this doesn't get unmounted cleanly
         EXEC=""
     else
         EXEC=exec
