when /proc is masked, wait for cleanup process to finish

diff --git a/cvmfsexec b/cvmfsexec
--- a/cvmfsexec
+++ b/cvmfsexec
@@ -6,6 +6,9 @@
 #   $CVMFSMOUNT and repositories can be umounted with $CVMFSUMOUNT.
 # Written by Dave Dykstra September 2019
 
+#set -x
+#PS4='c$$+ '
+
 VERSION=4.7
 
 usage()
@@ -210,6 +213,8 @@ export STDINCOPYFD
 # Note that within the here document, unprotected $ substitutions are
 #  done by the surrounding shell, and \$ is within the unshare shell
 unshare -rm $UNSHAREOPTS /bin/bash /dev/stdin "${@:-$SHELL}" <<!EOF-1!
+    #set -x
+    #PS4='c\$$+ '
     # now in the "fakeroot" namespace
     trap "rm -rf $TMPDIR" 0 # note that this does not carry through "exec"
 
@@ -299,10 +304,22 @@ unshare -rm $UNSHAREOPTS /bin/bash /dev/stdin "${@:-$SHELL}" <<!EOF-1!
     fi
 
     export CVMFSEXEC_CMDFD
+    exec {CVMFSEXEC_CMDFD}>$CMDFIFO1 
+
+    if [ -z "$UNSHAREOPTS" ]; then
+        # running without new process namespace, so more cleanup
+        #  needs to be done and our exit needs to wait for the
+        #  background process to finish cleaning up
+        EXEC=""
+    else
+        EXEC=exec
+    fi
 
     # quoting the here document's delimeter makes this nested shell not
     #  interpret $ substitutions, but the previous one still does
-    exec unshare -U /bin/bash /dev/stdin "\${@:-$SHELL}" {CVMFSEXEC_CMDFD}>$CMDFIFO1 <<'!EOF-2!'
+    \$EXEC unshare -U /bin/bash /dev/stdin "\${@:-$SHELL}" <<'!EOF-2!'
+        #set -x
+        #PS4='c\$$+ '
         # now in the user namespace
 
         export -n STDINCOPYFD
@@ -328,14 +345,18 @@ unshare -rm $UNSHAREOPTS /bin/bash /dev/stdin "${@:-$SHELL}" <<!EOF-1!
         else
             EXEC=exec
         fi
-        $EXEC "\$@" <&\$STDINCOPYFD {STDINCOPYFD}<&-
+        \$EXEC "\$@" <&\$STDINCOPYFD {STDINCOPYFD}<&-
 !EOF-2!
+
+    RET="\$?"
+    exec {CVMFSEXEC_CMDFD}>&-
+    # wait for background process to clean up
+    wait
+    exit \$RET
 
 !EOF-1!
 
 RET="$?"
-
 # wait for background process to clean up
 wait
-
 exit $RET
