disable rhel7-x86_64 with osg & egi, enable debian13, update to 4.48

diff --git a/makedist b/makedist
--- a/makedist
+++ b/makedist
@@ -141,8 +141,8 @@ if [ -z "$MACHTYPE" ]; then
         fi
         case "$VERS" in
             11) DISTRO=rhel; VERS=8;;
-            12) DISTRO=rhel; VERS=9;;
-            *)  echo "debian$VERS not supported, only 11 & 12 are" >&2
+            12|13) DISTRO=rhel; VERS=9;;
+            *)  echo "debian$VERS not supported, only 11 through 13 are" >&2
                 exit 2;;
         esac
     elif [ "$DISTRO" = "ubuntu" ]; then
@@ -241,24 +241,19 @@ case $1 in
         ;;
     osg)
         if [ $EL -lt 8 ]; then
-            REL=3.6
-            EXT=""
-        else
-            REL=24-main
-            EXT="/Packages/c"
+            echo "ERROR: unsupported OS for osg! Only rhel8 and up supported" >&2
+            exit 1
         fi
-        REPO=release
-        BASEURL="https://repo.opensciencegrid.org/osg/$REL/el$EL/$REPO/x86_64$EXT"
+        BASEURL="https://repo.opensciencegrid.org/osg/24-main/el$EL/release/x86_64/Packages/c"
         BASELIST="$(get_cvmfs_pkg_list $BASEURL)";;
     egi)
-        OS=centos$EL
-        if [ $EL -gt 8 ]; then
+        if [ $EL = 9 ] || ( [ $DISTRO = suse ] && [ $EL = 8 ] ); then
+             # In the suse case we don't actually get much from the egi
+             # distribution so the version mismatch is ok
              BASEURL="https://repository.egi.eu/sw/production/umd/5/al9/release/x86_64/"
-        elif [ $EL -eq 7 ]; then
-            BASEURL="https://repository.egi.eu/sw/production/umd/4/centos7/x86_64/updates"
         else
-          echo "ERROR: unsupported OS for egi! only centos7, almalinux9 supported." >&2
-          exit 1
+            echo "ERROR: unsupported OS for egi! Only rhel9 is supported" >&2
+            exit 1
         fi 
         BASELIST="$(get_cvmfs_pkg_list $BASEURL)";;
     default|none)
@@ -309,11 +304,6 @@ if [ "$ARCH" != "x86_64" ]; then
     #  we're looking at x86_64 version repositories for the config rpm
     INCLUDEHELPER=false
 fi
-if [ "$DISTTYPE" = egi ] && [ "$EL" = 8 ]; then
-    echo "egi's UMD does not yet support rhel8" 2>&1
-    exit 1
-fi
-
 
 URLS=""
 CVMFSURL=""
